import { Highlight, themes } from 'prism-react-renderer';
import styles from './CodeSidebar.module.css';

const eventsCode = `// Generated using EventPanel
// https://github.com/eventpanel/eventpanel-cli

export namespace AnalyticsEvents {
  /**
   * Events related to shopping and purchasing actions
   */
  export namespace ECommerceEvents {

    /**
     * Triggered when a user adds a product to the shopping cart
     * @param price Price of the product
     * @param productId Unique identifier of the product
     */
    export function addToCart(  
      price: number,
      productId: string,
    ): AnalyticsEvent {
      return {
        name: 'Add to Cart',
        parameters: {
          price: price,
          productId: productId,
        },
      };
    }

    /**
     * Triggered when a user starts the checkout process
     * @param cart Items in the cart
     */
    export function checkoutStarted(  
      cart: Record<string, unknown>,
    ): AnalyticsEvent {
      return {
        name: 'Checkout Started',
        parameters: {
          cart: cart,
        },
      };
    }

    export function purchaseCompleted(  
      orderIds: string[],
      total: number,
    ): AnalyticsEvent {
      return {
        name: 'Purchase Completed',
        parameters: {
          orderIds: orderIds,
          total: total,
        },
      };
    }
  }

  /**
   * Events related to user's first-time experience
   */
  export namespace OnboardingEvents {

    export function onboardingStarted(  
      source: Source,
    ): AnalyticsEvent {
      return {
        name: 'Onboarding Started',
        parameters: {
          source: source,
        },
      };
    }

    export function onboardingCompleted(  
      userId: string,
      duration: number | undefined,
    ): AnalyticsEvent {
      return {
        name: 'Onboarding Completed',
        parameters: {
          userId: userId,
          duration: duration,
        },
      };
    }
  }

  /**
   * Events related to user interactions
   */
  export namespace UserActions {

    export function profileViewed(  
      userId: string,
    ): AnalyticsEvent {
      return {
        name: 'Profile Viewed',
        parameters: {
          userId: userId,
        },
      };
    }

    export function settingsChanged(  
      setting: string,
      value: string,
    ): AnalyticsEvent {
      return {
        name: 'Settings Changed',
        parameters: {
          setting: setting,
          value: value,
        },
      };
    }
  }
}

// Custom types
export enum Source {
  Email = "email",
  Ads = "ads",
  Organic = "organic"
}

export interface AnalyticsEvent {
  name: string;
  parameters: Record<string, unknown>;
}`;

interface CodeSidebarProps {
  isOpen: boolean;
  onClose: () => void;
}

export function CodeSidebar({ isOpen, onClose }: CodeSidebarProps) {
  return (
    <>
      {/* Overlay */}
      <div 
        className={`${styles.overlay} ${isOpen ? styles.overlayVisible : ''}`}
        onClick={onClose}
        aria-hidden="true"
      />
      
      {/* Sidebar */}
      <aside className={`${styles.sidebar} ${isOpen ? styles.sidebarOpen : ''}`}>
        <div className={styles.header}>
          <div className={styles.headerContent}>
            <div className={styles.fileIcon}>
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
                <polyline points="14 2 14 8 20 8" />
                <line x1="16" y1="13" x2="8" y2="13" />
                <line x1="16" y1="17" x2="8" y2="17" />
                <polyline points="10 9 9 9 8 9" />
              </svg>
            </div>
            <div className={styles.fileInfo}>
              <span className={styles.fileName}>events.ts</span>
              <span className={styles.filePath}>analytics/events.ts</span>
            </div>
          </div>
          <button className={styles.closeButton} onClick={onClose} aria-label="Close sidebar">
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <line x1="18" y1="6" x2="6" y2="18" />
              <line x1="6" y1="6" x2="18" y2="18" />
            </svg>
          </button>
        </div>
        
        <div className={styles.badgeContainer}>
          <span className={styles.badge}>Generated by EventPanel CLI</span>
        </div>
        
        <div className={styles.codeContainer}>
          <Highlight
            theme={themes.nightOwl}
            code={eventsCode}
            language="typescript"
          >
            {({ style, tokens, getLineProps, getTokenProps }) => (
              <pre className={styles.pre} style={{ ...style, background: 'transparent' }}>
                <code className={styles.code}>
                  {tokens.map((line, i) => (
                    <div key={i} {...getLineProps({ line })} className={styles.line}>
                      <span className={styles.lineNumber}>{i + 1}</span>
                      <span className={styles.lineContent}>
                        {line.map((token, key) => (
                          <span key={key} {...getTokenProps({ token })} />
                        ))}
                      </span>
                    </div>
                  ))}
                </code>
              </pre>
            )}
          </Highlight>
        </div>
        
        <div className={styles.footer}>
          <div className={styles.stats}>
            <span className={styles.stat}>
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20" />
                <path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z" />
              </svg>
              TypeScript
            </span>
            <span className={styles.stat}>
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <line x1="4" y1="9" x2="20" y2="9" />
                <line x1="4" y1="15" x2="20" y2="15" />
                <line x1="10" y1="3" x2="8" y2="21" />
                <line x1="16" y1="3" x2="14" y2="21" />
              </svg>
              ~120 lines
            </span>
          </div>
          <a 
            href="https://github.com/nicosantux/eventpanel-cli" 
            target="_blank" 
            rel="noopener noreferrer"
            className={styles.link}
          >
            View on GitHub
            <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6" />
              <polyline points="15 3 21 3 21 9" />
              <line x1="10" y1="14" x2="21" y2="3" />
            </svg>
          </a>
        </div>
      </aside>
    </>
  );
}

// Toggle button component
interface CodeToggleButtonProps {
  onClick: () => void;
}

export function CodeToggleButton({ onClick }: CodeToggleButtonProps) {
  return (
    <button className={styles.toggleButton} onClick={onClick} aria-label="View generated code">
      <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
        <polyline points="16 18 22 12 16 6" />
        <polyline points="8 6 2 12 8 18" />
      </svg>
      <span>View Code</span>
    </button>
  );
}
